version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - curl -L https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.361/quarto-1.3.361-linux-amd64.deb -o quarto.deb
      - dpkg -x quarto.deb .
      - mv opt/quarto ./
      - rmdir opt
      - mkdir -p ~/.local/bin
      - ln -s "$(pwd)"/quarto/bin/quarto .
      - quarto --version


mkdocs:
  configuration: mkdocs/mkdocs.yml

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
      extra_requirements:
      - dev