version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - curl -L https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.361/quarto-1.3.361-linux-amd64.deb -o quarto.deb
      - dpkg -x quarto.deb .
      - rm quarto.deb
      - ln -s "$(pwd)"/opt/quarto/bin/quarto /home/docs/checkouts/readthedocs.org/user_builds/buck-rl-nbdev/envs/latest/bin
      - echo $PATH
      - quarto --version


mkdocs:
  configuration: mkdocs/mkdocs.yml

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
      extra_requirements:
      - dev