# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/Buck',
                'doc_host': 'https://kgoodrick-rl.github.io',
                'git_url': 'https://github.com/kgoodrick-rl/Buck',
                'lib_path': 'Buck'},
  'syms': {'Buck.core': {'Buck.core.foo': ('core.html#foo', 'Buck/core.py')}}}
